name: "Build"

on:
  push:
  # release:
  #   types: [published,prereleased]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ./build.sh
    - run: cp ./result/iso/*.iso img.iso
    - uses: actions/upload-artifact@v2
      with:
        name: iso
        path: img.iso
    # - uses: fnkr/github-action-ghr@v1
    #   env:
    #     GHR_PATH: img.iso
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
